const sampleRoutes = [
  {
    operatorName: 'Raj Mudra Premium',
    routeCode: 'RM101',
    busType: 'AC Sleeper',
    originCity: 'Pune',
    destinationCity: 'Solapur',
    departureTime: '22:15',
    arrivalTime: '05:30',
    travelDurationMins: 435,
    fare: 1299,
    availableSeats: 18,
    totalSeats: 32,
    rating: 4.8,
    ratingsCount: 2480,
    amenities: ['Blanket', 'Water Bottle', 'WiFi', 'Live Tracking'],
    boardingPoints: ['Shivajinagar', 'Katraj'],
    droppingPoints: ['Solapur Bypass', 'Murud'],
    daysOfOperation: ['Daily'],
    highlights: ['Host on-board', 'Snacks Included'],
  },
  {
    operatorName: 'Raj Mudra Express',
    routeCode: 'RM205',
    busType: 'AC Seater',
    originCity: 'Pune',
    destinationCity: 'Kolhapur',
    departureTime: '06:30',
    arrivalTime: '12:15',
    travelDurationMins: 345,
    fare: 899,
    availableSeats: 28,
    totalSeats: 40,
    rating: 4.5,
    ratingsCount: 1120,
    amenities: ['Charging Point', 'Live Tracking', 'Reading Light'],
    boardingPoints: ['Swargate', 'Hadapsar'],
    droppingPoints: ['Kolhapur ST Stand'],
    daysOfOperation: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    highlights: ['Fastest on route'],
  },
  {
    operatorName: 'Western Luxe',
    routeCode: 'WL782',
    busType: 'Electric Luxury',
    originCity: 'Mumbai',
    destinationCity: 'Pune',
    departureTime: '18:00',
    arrivalTime: '22:00',
    travelDurationMins: 240,
    fare: 1599,
    availableSeats: 10,
    totalSeats: 28,
    rating: 4.9,
    ratingsCount: 512,
    amenities: ['Recliner', 'Entertainment', 'WiFi', 'Snacks'],
    boardingPoints: ['BKC', 'Sion'],
    droppingPoints: ['Wakad', 'Baner'],
    daysOfOperation: ['Fri', 'Sat', 'Sun'],
    highlights: ['EV Fleet', 'Zero Noise Cabin'],
  },
  {
    operatorName: 'Konkan Connect',
    routeCode: 'KC310',
    busType: 'Non AC Sleeper',
    originCity: 'Pune',
    destinationCity: 'Goa',
    departureTime: '20:45',
    arrivalTime: '07:30',
    travelDurationMins: 645,
    fare: 999,
    availableSeats: 24,
    totalSeats: 36,
    rating: 4.3,
    ratingsCount: 870,
    amenities: ['Blanket', 'Charging Point'],
    boardingPoints: ['Kothrud Depot', 'Warje'],
    droppingPoints: ['Panaji', 'Mapusa'],
    daysOfOperation: ['Daily'],
    highlights: ['Sunrise arrival'],
  },
  {
    operatorName: 'Raj Mudra Rapid',
    routeCode: 'RM450',
    busType: 'AC Sleeper',
    originCity: 'Solapur',
    destinationCity: 'Hyderabad',
    departureTime: '23:10',
    arrivalTime: '06:00',
    travelDurationMins: 410,
    fare: 1199,
    availableSeats: 12,
    totalSeats: 30,
    rating: 4.6,
    ratingsCount: 1540,
    amenities: ['Water Bottle', 'Host', 'WiFi'],
    boardingPoints: ['Solapur Central'],
    droppingPoints: ['Miyapur', 'Lakdikapul'],
    daysOfOperation: ['Daily'],
    highlights: ['Luxury linen'],
  },
  {
    operatorName: 'Deccan Dayliner',
    routeCode: 'DD115',
    busType: 'Non AC Seater',
    originCity: 'Pune',
    destinationCity: 'Nashik',
    departureTime: '09:00',
    arrivalTime: '14:00',
    travelDurationMins: 300,
    fare: 699,
    availableSeats: 35,
    totalSeats: 45,
    rating: 4.1,
    ratingsCount: 640,
    amenities: ['Water Bottle'],
    boardingPoints: ['Nigdi', 'Shivajinagar'],
    droppingPoints: ['Nashik CBS'],
    daysOfOperation: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    highlights: ['Budget friendly'],
  },
];

export default sampleRoutes;
